### ISSUE TITLE
wirelogd v1.0.3 cannot be run without aruments

### ISSUE THREAD

**Issue by mkrogh** [nikaro/wirelogd#41]
Installing wirelogd using the debian package from release v1.0.3 the service throws the following exception:

```
Apr 26 09:21:08 wireguard-test-01 systemd[1]: Started WireGuard Logging.
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]: panic: runtime error: index out of range [1] with length 1
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]: goroutine 1 [running]:
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]: main.initConfig()
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]:         /home/runner/work/wirelogd/wirelogd/wirelogd.go:102 +0x4c6
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]: github.com/spf13/cobra.(*Command).preRun(...)
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]:         /home/runner/work/wirelogd/wirelogd/vendor/github.com/spf13/cobra/command.go:946
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]: github.com/spf13/cobra.(*Command).execute(0xa7f800, {0xc000014240, 0x0, 0x0})
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]:         /home/runner/work/wirelogd/wirelogd/vendor/github.com/spf13/cobra/command.go:876 +0x563
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]: github.com/spf13/cobra.(*Command).ExecuteC(0xa7f800)
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]:         /home/runner/work/wirelogd/wirelogd/vendor/github.com/spf13/cobra/command.go:1044 +0x3bd
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]: github.com/spf13/cobra.(*Command).Execute(...)
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]:         /home/runner/work/wirelogd/wirelogd/vendor/github.com/spf13/cobra/command.go:968
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]: main.main()
Apr 26 09:21:08 wireguard-test-01 wirelogd[3188]:         /home/runner/work/wirelogd/wirelogd/wirelogd.go:210 +0x25
Apr 26 09:21:08 wireguard-test-01 systemd[1]: wirelogd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

It seems like wirelogd cannot be run without arguments in the current release.
Running it with `--config /etc/wirelogd/config.toml` works.

Other info:
OS: ubuntu 22.04
Installed using `dpkg -i`

**Comment by mkrogh** [comment]
Still a problem using wirelogd_1.0.4_linux_amd64.deb, it throws:

```
Apr 27 06:16:46 vpn-01 systemd[1]: Started WireGuard Logging.
Apr 27 06:16:46 vpn-01 wirelogd[883583]: panic: runtime error: index out of range [1] with length 1
Apr 27 06:16:46 vpn-01 wirelogd[883583]: goroutine 1 [running]:
Apr 27 06:16:46 vpn-01 wirelogd[883583]: main.initConfig()
Apr 27 06:16:46 vpn-01 wirelogd[883583]:         /home/runner/work/wirelogd/wirelogd/wirelogd.go:102 +0x535
Apr 27 06:16:46 vpn-01 wirelogd[883583]: github.com/spf13/cobra.(*Command).preRun(...)
Apr 27 06:16:46 vpn-01 wirelogd[883583]:         /home/runner/work/wirelogd/wirelogd/vendor/github.com/spf13/cobra/command.go:970
Apr 27 06:16:46 vpn-01 wirelogd[883583]: github.com/spf13/cobra.(*Command).execute(0xa6b980, {0xc000014260, 0x0, 0x0})
Apr 27 06:16:46 vpn-01 wirelogd[883583]:         /home/runner/work/wirelogd/wirelogd/vendor/github.com/spf13/cobra/command.go:900 +0x563
Apr 27 06:16:46 vpn-01 wirelogd[883583]: github.com/spf13/cobra.(*Command).ExecuteC(0xa6b980)
Apr 27 06:16:46 vpn-01 wirelogd[883583]:         /home/runner/work/wirelogd/wirelogd/vendor/github.com/spf13/cobra/command.go:1068 +0x3bd
Apr 27 06:16:46 vpn-01 wirelogd[883583]: github.com/spf13/cobra.(*Command).Execute(...)
Apr 27 06:16:46 vpn-01 wirelogd[883583]:         /home/runner/work/wirelogd/wirelogd/vendor/github.com/spf13/cobra/command.go:992
Apr 27 06:16:46 vpn-01 wirelogd[883583]: main.main()
Apr 27 06:16:46 vpn-01 wirelogd[883583]:         /home/runner/work/wirelogd/wirelogd/wirelogd.go:210 +0x25
Apr 27 06:16:46 vpn-01 systemd[1]: wirelogd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 27 06:16:46 vpn-01 systemd[1]: wirelogd.service: Failed with result 'exit-code'
```

**Comment by nikaro** [comment]
Fixed in https://github.com/nikaro/wirelogd/releases/tag/v1.0.5 (and tested this time...)
